### ISSUE TITLE
로그인 동작 이슈

### ISSUE THREAD

**Issue by jkpark** [matgip/TastyEstate#30]
https://github.com/matgip/TastyEstate/blob/48699dca727e19053a4370ba921662be0e86cf75/frontend/src/components/Login/LoginKakao.vue#L18

로그인 시도 하기전에 getUser() 먼저 불러서 로그인됐는지 안됐는지 체크 필요할듯?

**Comment by junhong91** [comment]
보다보니 accessToken이랑 refreshToken을 카카오에서 주는거같은데 이걸 어떻게 써야되는지 잘 모르겟음

**Comment by junhong91** [comment]
카카오로부터 토큰을 받았기 때문에 getUser가 동작하는건가??

**Comment by junhong91** [comment]
6db14b9c8fad334d61449c85bb36fefb93af10b3
반영 완료
