### ISSUE TITLE
Store 남용

### ISSUE THREAD

**Issue by jkpark** [matgip/TastyEstate#44]
BaseChkBox.vue 코드를 보면 사용자가 체크박스 클릭했을 때 store에 저장되도록 구현되어 있음
https://github.com/matgip/TastyEstate/blob/412b1cc71b9bfd88eccd5e7a00a2c9e7151a27a3/frontend/src/common/BaseChkBox.vue#L56
이럴 필요 있나?
변경된 selected는 상위 컴포넌트로 emit 해주고, 상위컴포넌트에서 필요한 작업하면 되잖아.

이런 불필요한 store쓰는 작업을 줄일 필요가 있을듯

**Comment by junhong91** [comment]
depth가 깊어질수록 emit를 사용하면 중간자는 불필요한 코드가 생김<-이걸 위해 등장한게 store
오히려 emit 남용이 더 좋지 않음

기존 코드를 변경하고 싶으면 차라리 depth를 낮추는 방법으로 생각해보는게 좋을ㄷ ㅡㅅ

**Comment by junhong91** [comment]
1 depth 만 emit사용이 적절할듯

**Comment by jkpark** [comment]
자식컴포넌트에서  data changing event가 발생하면 안됨.
data changing event 필요시 callback 함수로 돌려주도록 구현.
(button컴포넌트가 부모로부터 @click 콜백 메소드를 받는 것처럼)

**Comment by junhong91** [comment]
- Base 컴포넌트를 사용하는 경우, Callback으로 수정
- 과도하게 나눠진 건 다시 합침
  - dialog / contract / price / kindess store 삭제
