### ISSUE TITLE
BaseChkBox에서 index를 받는 이유

### ISSUE THREAD

**Issue by jkpark** [matgip/TastyEstate#48]
https://github.com/matgip/TastyEstate/blob/e96ed916d1c0c9ec59c7794b4f6de50212c3c3fd/frontend/src/common/BaseCheckBox.vue#L28

BaseChkBox에서 index를 받을 이유가 없음.

ReviewDialogButton.vue 에서 chkBoxes array의 index를 전달해주기 위해 저렇게 해놓은거 같은데
저러면 재사용성 떨어질듯.

수정필요

**Comment by jkpark** [comment]
그리고 
[        <v-list-item v-bind="listItemProps" :key="`item-${i}`" :value="item.value">](https://github.com/matgip/TastyEstate/blob/e96ed916d1c0c9ec59c7794b4f6de50212c3c3fd/frontend/src/common/BaseCheckBox.vue#L13)
에서 key를 저렇게 받는 이유는 머임?? 몰라서 물어봄

**Comment by junhong91** [comment]
:key를 받는거는 아마 안쓰면 check된게 리랜더링이 안될거야 아마도?
원래 그 이유로 key주니까

**Comment by jkpark** [comment]
근데 `item-${i}` 의 의미는머임? 걍 `:key=i` 해도 될텐데

**Comment by junhong91** [comment]
ㅇㅇ 아마 상관없을걸 레퍼런스 가지고 온거라 그런거임

**Comment by junhong91** [comment]
array로 짜놨는데, 사실 "string" to object형태의 자료구조가 있으면 그거 쓰면 index필요없어질거 같은데
더 좋은방법 찾아봐야할듯

**Comment by junhong91** [comment]
onClick이 됬을때 DOM element의 값으로 확인 가능하면 index를 삭제할 수 있을 듯

**Comment by jkpark** [comment]
여래개의 chkbox group을 가지고 있는건 ReviewDialogButton.vue  에서의 문제고,
baseCheckBox 에서는 index 같은 걸 넘겨받을 이유가 없지..
plain js에서 click listener어떻게 구현했는지 찾아봐야될듯

**Comment by junhong91** [comment]
plain js에서 click listener어떻게 구현했는지 찾아봐야될듯
> ㅇㅇ 바로 위에서 언급한 내용인데 onchange시에 돔 element에 접속해서 data나 prop값을 보면 인덱스가 필요앖아질듯?

**Comment by junhong91** [comment]
index 삭제
commit: c3737a1827940cd15c88ba6e830a65d451a1e3d0
