### ISSUE TITLE
RealEstate 네이밍?

### ISSUE THREAD

**Issue by jkpark** [matgip/TastyEstate#56]
RealEstate 는 부동산(아파트 등 건물)이라는 뜻이라 바꿔야되지 않을까?

찾아보니까 공인중개소가 영어로 Real Estate Agency인거 같은데...

**Comment by junhong91** [comment]
그러네 RealEstate는 아파트 건물등을 의미하는 거니까, Agency를 붙이는게 좋을듯

**Comment by jkpark** [comment]
RealEstateAgency 할까 아니면 그냥 Agency 로 할까?
난 후자가 더 나은듯

**Comment by junhong91** [comment]
ㅇㅇ 나도 RealEstateAgency는 너무 기니까 Agency가 좋을 듯.
