### ISSUE TITLE
RealEstate의 호출방식과 store 구조 문제점

### ISSUE THREAD

**Issue by jkpark** [matgip/TastyEstate#57]
1. 맵에서 마커를 클릭하면 `MapSearch.vue` 파일에서 3개의 store에 dispatch 하는 형태로 구현되어있음.
```
        await this.$store.dispatch("updateRealEstate", estate);
        await this.$store.dispatch("getLikes", estate.id);
        await this.$store.dispatch("getStars", estate.id);
```
estateStore, likesStore, starsStore를 나눌 필요가 없지 않음? 통합시키면 좋을듯

2. 그리고 estate의 mutation은 RealEstate.vue에서 직접하고 있음.
주변 부동산 보여줄 때 RealEstate.vue를 재사용 하려면 estate정보를 props로 받아야 될듯

3. 그리고 store보니까 하나의 부동산만 저장할 수 있게 되어 있는데 
주변 부동산 정보도 보여 줄려면 여러 개의 부동산을 담을 수 있도록 수정 해야 될 듯.

**Comment by junhong91** [comment]
1. 맵에서 마커를 클릭하면 MapSearch.vue 파일에서 3개의 store에 dispatch 하는 형태로 구현되어있음.
        await this.$store.dispatch("updateRealEstate", estate);
        await this.$store.dispatch("getLikes", estate.id);
        await this.$store.dispatch("getStars", estate.id);
estateStore, likesStore, starsStore를 나눌 필요가 없지 않음? 통합시키면 좋을듯
> ㅇㅇ 동감. 합치고 BE에서 controller가 처리하는 방식이 좋을듯

**Comment by junhong91** [comment]
2. 그리고 estate의 mutation은 RealEstate.vue에서 직접하고 있음.
주변 부동산 보여줄 때 RealEstate.vue를 재사용 하려면 estate정보를 props로 받아야 될듯

**Comment by junhong91** [comment]
3. 그리고 store보니까 하나의 부동산만 저장할 수 있게 되어 있는데
주변 부동산 정보도 보여 줄려면 여러 개의 부동산을 담을 수 있도록 수정 해야 될 듯.
> 이 부분을 store에서 estates[] 배열로 저장할지 고려 중임.

**Comment by junhong91** [comment]
완료: stars / likes는 이제 BE에서 트랜잭션으로 묶어서 처리됨
